### ISSUE TITLE
Detect article on source meta page

### ISSUE THREAD

**Issue by andrenarchy** [paperhive/paperhive-chrome-extension#3]
Additional to detecting the article when opening the PDF file, it would be great to also detect it on article meta pages like [this](http://arxiv.org/abs/1208.0264) (instead of only the corresponding [pdf](http://arxiv.org/pdf/1208.0264v4.pdf)).

**Comment by nschloe** [comment]
Should be possible via the `citation_pdf_url` meta tag (on arXiv).

**Comment by andrenarchy** [comment]
Nice! We could also simply use the meta page URL and feed it to the `source` API endpoint. This one already recognizes that http://arxiv.org/abs/1208.0264 is the same as http://arxiv.org/pdf/1208.0264v4.pdf.

**Comment by nschloe** [comment]
Fixed.
