### ISSUE TITLE
resolve doi when adding article

### ISSUE THREAD

**Issue by nschloe** [paperhive/paperhive-chrome-extension#32]
Some pages don't provide a DOI meta tag although they have one. [ScienceDirect](http://www.sciencedirect.com/science/article/pii/S0022000011000778) is an example.

We could still identify that these pages are associated with a DOI by resolving the DOI when including the article into the PaperHive database and storing that URL. The extension could then searchByUrl.

**Comment by andrenarchy** [comment]
Fixed in 1.3.1 by making use of the new `documents/remote` endpoint.
