### ISSUE TITLE
icons in distribution wrong

### ISSUE THREAD

**Issue by nschloe** [paperhive/paperhive-chrome-extension#65]
![shot](https://cloud.githubusercontent.com/assets/181628/13036274/2545dac4-d363-11e5-8dcd-eb82efad9ded.png)

**Comment by nschloe** [comment]
Should be fixed now.

**Comment by andrenarchy** [comment]
Nope. ;)

**Comment by andrenarchy** [comment]
Seems to be fixed in Chrome 51 and Firefox 47.
